.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. flirtcoin_qt test_flirtcoin_qt
clean: FORCE
	$(MAKE) -C .. flirtcoin_qt_clean test_flirtcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_flirtcoin_qt_check
flirtcoin-qt flirtcoin-qt.exe: FORCE
	 $(MAKE) -C .. flirtcoin_qt
