#!/bin/bash

# This is a thin wrapper around flirtcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using flirtcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_FLIRTCOIND

# Grab the value of $REAL_FLIRTCOINCLI which may be flirtcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_FLIRTCOINCLI}" "$@" | sed 's/\r//'
